version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "cron"
      cron: "30 1 * * 1"
    open-pull-requests-limit: 0
    allow:
      - dependency-type: "direct"
    labels:
      - "dependencies"
      - "python"
