"""Prompts for the MutateAgent mutation modes."""


START_PROMPT_TEMPLATE = "You are a computer science researcher working at DeepMind. You will be given a Python function that contains rules to detech cloud anomaly in microservices.\nYou are working on a task to mutate the rules in the code for a evolutionary algorithm. You should achieve the task in the following steps:\n\n1. You are given a Python function `inference(sample: np.ndarray) -> np.ndarray` that writes various rules to classify samples as normal or abnormal.\n   - The function processes a `numpy` array of shape ({chunk_size}, 2), where each row is a tuple of (value, index).\n   - The function determines if a given sample follows a pattern similar to previously observed normal or abnormal samples.\n   - It returns a `numpy` array of shape ({chunk_size}), where each index is labeled as:\n     - `1` → Abnormal\n     - `0` → Normal\n    - The function contains rules to detect if the given sample is abnormal or normal.\n    - The code can contains from 1-n normal rules and 1-n abnormal rules.\n    - The code will be given in the following format:\n\n    ##### CODE\n    ```python\n    # import necessary libraries\n    def inference(sample: np.ndarray) -> np.ndarray:\n        # Comment to describe how normal data behave\n        # Normal Rule 1\n        # Normal Rule 2\n        ...\n        # Normal Rule n\n        \n\n        # Code to detect if the given sample is abnormal\n        # Abnormal Rule 1\n        if ...\n        # Abnormal Rule 2\n        if ...\n        ...\n        # Abnormal Rule n\n        if ...\n\n        # return labels as a 1d numpy array indicating abnormal/normal of each index\n    ```\n    ##### END OF CODE\n\n2. You should output the mutated code following the same format as the input code, wrapping the code with ```python as the first line and ``` as the last line. Make sure to label normal rules description with # Normal Rule and abnormal rules description with # Abnormal Rule according to the file format.\n3. **DO NOT** hardcode any labels or example data in the function. You should only change the rules in the code.\n4. **DO NOT** change the function signature or input/output format. Modify only the rules.\n5. **DO NOT** delete any comments that start with # Normal Rule. You must only mutate the Abnormal Rules.\n6. You should make sure the python code is correct and can be executed without any error.\n7. If your code uses any external libraries, you should include the import statements in the code.\n8. You should wrap the code with ```python as the first line and ``` as the last line. You must only use ```python and ``` to wrap your code for only once, don't use them for any other purpose.\n"

DEFAULT_PROMPT_SUBSTITUTED = '\n9. You can consider inspiration from this set of example ideas:\n\nExample mutate rule:\n\n- remove one rule from the code\n- remove some rules from the code\n- add one new rule to the code\n- add some new rules to the code\n\n- change condition in one of the rules\n- change threshold in one of the rules\n\n- change the order of the rules\n- add or remove logical operators in the rules\n- random Insertion or Deletion of Conditions in the rules\n- change the comparison operator in the conditions\n\n- make rule dependent on the previous rule\n- break rule dependency\n\n- add noise to sample from a distribution\n\nCraft your own mutation rules and applied it to the code.  Choose which one you think would be the best\n10. Add a comment on the first line of the code (before inference function) to indicate the action you have done with the rules.\n'

DELETE_PROMPT = "\n9. You must select one or more rule(s) to delete from the code. If there is only one rule in the code, replace it with a random rule. DON'T ADD NEW RULES OR REPLACE DELETED ONE WITH NEW RULES.\n10. Make sure to remove any comments or code that are related to the deleted rule.\n11. Add a comment on the first line of the code (before inference function) to indicate the action you have done with the rules.\n"

CHANGE_PROMPT = '\n9. You must select one or more rule(s) to change from the code. The change could be changing the condition, threshold, comparison operator, or any other minor change but the high-level logic should remain the same.\n10. Add a comment on the first line of the code (before inference function) to indicate the action you have done with the rules.\n'

REMOVE_ALL_BUT_ONE_PROMPT = "\n9. You must remove all but one rule from the code. Please make sure to keep the most important rule. DON'T ADD NEW RULES OR REPLACE DELETED ONE WITH NEW RULES.\n10. Make sure to remove any comments or code that are related to the deleted rules.\n11. Add a comment on the first line of the code (before inference function) to indicate the action you have done with the rules.\n"


def generate_mutate_prompt(chunk_size: int, type: str = "free") -> str:
    start_prompt = START_PROMPT_TEMPLATE.format(chunk_size=chunk_size).strip()
    if type == "free":
        return start_prompt + "\n" + DEFAULT_PROMPT_SUBSTITUTED.strip()
    if type == "remove(s)":
        return start_prompt + "\n" + DELETE_PROMPT.strip()
    if type == "change-only":
        return start_prompt + "\n" + CHANGE_PROMPT.strip()
    if type == "remove-all-but-one":
        return start_prompt + "\n" + REMOVE_ALL_BUT_ONE_PROMPT.strip()
    return ""
